---
- name: nodeinit
  hosts: localhost
  become: true
  tasks:

  - name: Add the NodeSource package signing key
    ansible.builtin.apt_key:
      id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

  - name: Add the NodeSource apt repository
    vars:
      url: https://deb.nodesource.com/
      version: node_16.x
    ansible.builtin.apt_repository:
        repo: "deb {{ url }}{{ version }} {{ ansible_distribution_release }} main"

  - name: Install Node.js
    ansible.builtin.apt:
      name: nodejs
